language: python
sudo: false
python:
  - 2.7
before_install:
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - ./bin/buildout -N -t 3 -c zodb5.cfg
script:
  - ./bin/test
